import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../StylesConfig/global.scss';
import { GlobalHeader } from "@/Components/GlobalHeader/GlobalHeader";
import { GlobalShareInSocialMedia } from "@/Components/GlobalShareInSocialMedia/GlobalShareInSocialMedia";
import { GlobalFooter } from "@/Components/GlobalFooter/GlobalFooter";
import { GlobalInvitacionAOtrasSecciones } from "@/Components/GlobalInvitacionAOtrasSecciones/GlobalInvitacionAOtrasSecciones";
import { GlobalAgradecimientos } from "@/Components/GlobalAgradecimientos/GlobalAgradecimientos";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Raul Acosta Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icons/mage.ico" />
      </head>
      <body className={inter.className}>
        <section>
          <GlobalHeader />
        </section>
        <section>
          <GlobalShareInSocialMedia />
        </section>
        <div className="containerPage">
          <div className="innerPage">
            <section>
              {children}
            </section>
            <section>
              <GlobalInvitacionAOtrasSecciones />
            </section>
            <section>
              <GlobalAgradecimientos/>
            </section>
          </div>
        </div>
        <section>
          <GlobalFooter />
        </section>
      </body>
    </html>
  );
}
